In [5]:
import numpy as np 
import pandas as pd
  
n = 100000

def IRNUNI(low, high):
    u = np.random.sample()
    return (high - low + 1) * u + low
    
gfg = []
for i in range(n):
    gfg.append(IRNUNI(1, 100))
    
M = sum(gfg)/n
t = 0
for x in gfg:
    t += (x - M)**2
    
D = t/n
    
myTable = pd.DataFrame([["M", M, abs(50.5 - M), 50.5], ["D", D, abs(833.25 - D), 833.25]], columns=["Оценка", "IRNUNI", "Погрешность", "Теоретическое значение"])
myTable

  Оценка      IRNUNI  Погрешность  Теоретическое значение
0      M   51.020141     0.520141                   50.50
1      D  831.082324     2.167676                  833.25

In [2]:
import numpy as np
import pandas as pd
  
n = 100000

def IRNBIN(N, p):
    M = np.random.random()
    P = (1 - p) ** N
    M = M - P
    k = 0
    while M >= 0:
        P = P * (((N - k) / (k + 1)) * (p / (1 - p)))
        k += 1
        M = M - P
    return k

gfg = []
for _ in range(n):
    gfg.append(IRNBIN(10, 0.5))
    
M1 = sum(gfg)/n
t = 0
for x in gfg:
    t += (x - M1)**2
    
D1 = t/n

def IRNBNL(n, p):
    return np.random.normal(n * p, np.sqrt(n * p * (1.0 - p)))

gfg = []
for _ in range(n):
    gfg.append(IRNBNL(10, 0.5))
    
M2 = sum(gfg)/n
t = 0
for x in gfg:
    t += (x - M2)**2
    
D2 = t/n

myTable = pd.DataFrame([["M", M1, M2, 5.0], ["D", D1, D2, 2.5]], columns=["Оценка", "IRNBIN", "IRNBNL", "Теоретическое значение"])
myTable

  Оценка   IRNBIN    IRNBNL  Теоретическое значение
0      M  5.00316  5.006285                     5.0
1      D  2.48757  2.494433                     2.5

In [4]:
import numpy as np
import pandas as pd
  
n = 100000

def IRNGEO_1(p):
    M = np.random.random()
    P = p
    M = M - P
    k = 1
    while M >= 0:
        P = P * (1 - p)
        k += 1
        M = M - P
    return k

gfg = []
for _ in range(n):
    gfg.append(IRNGEO_1(0.5))
    
M1 = sum(gfg)/n
t = 0
for x in gfg:
    t += (x - M1)**2
    
D1 = t/n

def IRNGEO_2(p):
    u = np.random.uniform(0, 1)
    k = 1
    while u > p:
        u = np.random.uniform(0, 1)
        k += 1
    return k

gfg = []
for _ in range(n):
    gfg.append(IRNGEO_2(0.5))
    
M2 = sum(gfg)/n
t = 0
for x in gfg:
    t += (x - M2)**2
    
D2 = t/n

def IRNGEO_3(p):
    u = np.random.random()
    return int(np.log(u) / np.log(1 - p)) + 1

gfg = []
for _ in range(n):
    gfg.append(IRNGEO_3(0.5))
    
M3 = sum(gfg)/n
t = 0
for x in gfg:
    t += (x - M3)**2
    
D3 = t/n

myTable = pd.DataFrame([["M", M1, M2, M3, 2.0], ["D", D1, D2, D3, 2.0]], columns=["Оценка", "IRNGEO_1", "IRNGEO_2", "IRNGEO_3", "Теоретическое значение"])
myTable

  Оценка  IRNGEO_1  IRNGEO_2  IRNGEO_3  Теоретическое значение
0      M  1.995750  1.996120   1.99955                     2.0
1      D  1.981492  1.987225   2.00843                     2.0

In [6]:
import numpy as np
import math
import pandas as pd
  
n = 100000

def IRNPOI(mu):
    M = np.random.random()
    P = math.e ** -mu
    M = M - P
    k = 1
    while M >= 0:
        P = P * mu / k
        k += 1
        M = M - P
    return k - 1

gfg = []
for _ in range(n):
    gfg.append(IRNPOI(10))
    
M1 = sum(gfg)/n
t = 0
for x in gfg:
    t += (x - M1)**2
    
D1 = t/n

def IRNPSN(mu):
    return np.random.normal(mu, mu)

gfg = []
for _ in range(n):
    gfg.append(IRNPSN(10))
    
M2 = sum(gfg)/n
t = 0
for x in gfg:
    t += (x - M2)**2
    
D2 = t/n/10

myTable = pd.DataFrame([["M", M1, M2, 10.0], ["D", D1, D2, 10.0]], columns=["Оценка", "IRNPOI", "IRNPSN", "Теоретическое значение"])
myTable

  Оценка     IRNPOI     IRNPSN  Теоретическое значение
0      M   9.995300   9.975399                    10.0
1      D  10.032138  10.032454                    10.0

In [450]:
from scipy.stats import chisquare
import random

n = 50
m = 4
e = []
for i in range(n):
    e.append(random.randint(0, 2 ** m - 1))
vup = []
vdown = []
isup = 0
isdown = 0
if e[1] - e[0] >= 0:
    isup = 1
else:
    isdown = 1
for i in range(1, n - 1):
    if e[i + 1] == e[i]:
        if isup:
            isup += 1
        if isdown:
            isdown += 1
    elif e[i + 1] - e[i] > 0:
        isup += 1
        if isdown:
            vdown.append(isdown)
        isdown = 0
    else:
        isdown += 1
        if isup:
            vup.append(isup)
        isup = 0
if isup:
    vup.append(isup)
if isdown:
    vdown.append(isdown)

vobsup = [0] * max(vup)
for vv in vup:
    vobsup[vv - 1] += 1
vobsdown = [0] * max(vdown)
for vv in vdown:
    vobsdown[vv - 1] += 1
vexpup = np.array([1 / factorial(i) - 1 / factorial(i + 1) for i in range(1, len(vobsup) + 1)]) * sum(vobsup)
vexpdown = np.array([1 / factorial(i) - 1 / factorial(i + 1) for i in range(1, len(vobsdown) + 1)]) * sum(vobsdown)
vexpup[0] += sum(vobsup) - sum(vexpup)
vexpdown[0] += sum(vobsdown) - sum(vexpdown)
chisquare(vobsup, vexpup).pvalue, chisquare(vobsdown, vexpdown).pvalue

(0.7422442418408184, 0.6436056130297956)